### ISSUE TITLE
运行报错类没有定义

### ISSUE THREAD

**Issue by TIS-OMiddle** [xtuhcy/gecco-htmlunit#1]
HtmlUnitDownloder.java中第66行
`HttpHost proxy = Proxys.getProxy();`
这个Proxys接口没有import进来，而且也没有getProxy()这个静态方法，参照了HttpClientDownloader.java的写法，大概是想这样？
```
HttpHost proxy = null;
Proxys proxys = ProxysContext.get();
boolean isProxy = ProxysContext.isEnableProxy();
if(proxys != null && isProxy) {
	webRequest.setProxyHost(proxy.getHostName());
	webRequest.setProxyPort(proxy.getPort());
}
```

**Comment by guichuanhai** [comment]
这行改成这样貌似就可以了
`HttpHost proxy = SpiderThreadLocal.get().getEngine().getProxysLoader().getProxy();`
